### ISSUE TITLE
More detailed documentation on how to install the plugin.

### ISSUE THREAD

**Issue by janfiess** [monsieurgustav/UE4-OSC#26]
Could you please provide expanded installation instructions? Right, I´m not the first one having problems to get UE4-OSC running. Bit I´m sure, I´m not the last one either. I´ve been troubleshooting for days and got lost in trial and error. A video tutorial would be best, but a written manual with every step would be great, too.

**Comment by ya7gisa0** [comment]
agree with @fabifiess .

**Comment by monsieurgustav** [comment]
I added an example project, in Examples/OscDemo.
You just need Visual Studio 2015 Community installed (with C++ components) and open the *.uproject.

**Comment by fabifiess** [comment]
Hi Guillaume,

sorry for my late reply. I spent my last few days on a trip without
internet...
That´s great news! Of course I will test your example project. By the way I
was now able to get your plugin installed since UE 4.11 is available here.
In combination with VS 2015 it does the trick - just as you proposed.
Unfortunately I will not be able to do more testing until the end of the
week. But I am very excited :-)
Thank you for this great message!

Best wishes
Fabi

2016-04-07 20:15 GMT+02:00 Guillaume Buisson <notifications@github.com>:

**Comment by lagauche** [comment]
Do you need VS 2015 or does VS 2017 also work? I have the plugin working and I built it with VS2015, but I'd prefer to uninstall VS2015 if we don't need it for this plugin anymore : )

**Comment by monsieurgustav** [comment]
VS2017 should work, but I don't use it myself: try and tell me! :)
