### ISSUE TITLE
Possibility to define a default port for send targets?

### ISSUE THREAD

**Issue by HughMacdonald** [monsieurgustav/UE4-OSC#47]
It turns out that the issue I came across before was because I'd put a send target in without a port, which meant that it was then trying to send data to 0.0.0.0:0

Inspired by this, what do you think to having, in the preferences, a "Default Port" option, and then allowing targets to be defined either by ip:port or just ip?

Happy to make the changes myself if you think that this is a good way to go.

**Comment by monsieurgustav** [comment]
Hi Hugh!
Sorry I took ages to answer this one...

To solve that kind of issue, I prefer to add some "validation" to the user input, rather than relying on a hidden behavior trying to understand what the user actually wants.
Unfortunately, I didn't find a way to inform the user of bad inputs (red borders or like).

So: I've just pushed some code that read the "SendTargets" settings and modify an element when it misses a proper address and/or port.

I think it solves the "0.0.0.0:0" issue. It is not exactly what you requested though (especially, I hard-coded the default port). Feel free to comment!
